components/d2l-module-link.html, test/d2l-module-link.html
- Turing numbers into strings before they are sent to localizing method. 
- Fixing a bug that shows count for 0 of 0 when the module is empty
=> US97250 TA125731 TA125732 Fixing count defects for modules

components/d2l-module-link.html
Replicating the open module on load given the current activity, also handles module open and closing when the activity is changedq
=> US95939 TA125746 Replicating the open module on load given the current activity

demo/data/l1-module1.json, demo/data/l1-module2.json, demo/data/l2-module1.json, demo/data/l4-optional-completion-module.json, demo/data/l4-required-completion-module.json, demo/data/lesson1.json, demo/data/lesson2.json, demo/data/lesson3.json, demo/data/lesson4.json, demo/data/sample2.json, demo/data/unit1.json, demo/data/unit2.json, demo/index.html, test/data/l1-module1.json, test/data/l1-module2.json, test/data/l2-module1.json, test/data/l4-optional-completion-module.json, test/data/l4-required-completion-module.json, test/data/lesson1.json, test/data/lesson2.json, test/data/lesson3.json, test/data/lesson4.json, test/data/sample2.json, test/data/unit1.json, test/data/unit2.json
Updating the test and demo counts to reflect the new entity from the server
=> Update test and demo data to reflect sequence-description completion counts

components/d2l-module-link.html
Ruling out the completion counts entity that is adding an blank activity to the navigation
=> Filtering out the completion status subentity

components/d2l-module-link.html
Fixing the closeModule method, consider both test and real data structures
=> Fixing the closeModule method

bower.json, package-lock.json, test/d2l-activity-link.html, test/d2l-completion-status.html, test/d2l-lesson-header.html, test/d2l-module-link.html, test/d2l-sequence-navigator-activity.html, test/d2l-sequence-navigator-item.html
https://rally1.rallydev.com/#/15545269080ud/detail/task/226740798392
https://rally1.rallydev.com/#/15545269080ud/detail/task/227292092924
=> TA125917 TA125849 Making sure the test renders the dynamic elements

components/d2l-completion-status.html, demo/data/activity2.json, demo/data/activity3.json, demo/data/l1-module1.json, demo/data/lesson1.json, test/d2l-sequence-navigator-activity.html, test/data/activity2.json, test/data/activity3.json, test/data/l1-module1.json, utility/completion-status-mixin.html
https://rally1.rallydev.com/#/15545269080/detail/userstory/221603123812
(no tooltip yet because I haven't gotten the details about how to do that)
=> add exempt indicator

components/d2l-completion-status.html, components/d2l-module-link.html, components/d2l-sequence-navigator-item.html, d2l-sequence-navigator.html, lang/en.json, localize-behavior.html, package-lock.json
[RALLY](https://rally1.rallydev.com/#/15545269080ud/detail/userstory/237779530676)
Adding aria-labels, and langterms for completeion, d2l-accordion has been fixed, adding tab indexs
=> US98671 TA126882 Adding aria-labels for completion and tab index

components/d2l-progress-bar.html, d2l-sequence-navigator.html
[RALLY](https://rally1.rallydev.com/#/15545269080ud/detail/userstory/237779530676)
Adding progressbar role to the progress bar and adding tabindex to le…sson header and end of lesson
=> A11y on lesson header and end of lesson

components/d2l-progress-bar.html
[RALLY](https://rally1.rallydev.com/#/15545269080ud/detail/userstory/237779530676)
=> Screen Readers were not reading out the progress bar at 0%

components/d2l-module-link.html
[RALLY](https://rally1.rallydev.com/#/15545269080ud/detail/task/250027914988)
Applying this change in the front end
https://git.dev.d2l/projects/CORE/repos/le/pull-requests/11697/overview
=> Filtering subentities of modules that are unavailable activities

d2l-sequence-navigator.html, lang/en.json, localize-behavior.html
Linking the end-of-lesson link to the end-of-sequence entity for the given root href.
Given the nature of the demo with JSON files and their extensions I haven't thought of a good way to support this.
=> US99150 TA125617  Nav bar "End of Lesson" link should link to this page

d2l-sequence-navigator.html
accidentally removed this from @lawong-d2l's PR
=> put back cursor pointer

components/d2l-activity-link.html, components/d2l-lesson-header.html, components/d2l-module-link.html, components/d2l-sequence-navigator-item.html
reference: https://github.com/BrightspaceUI/typography/blob/master/d2l-typography-shared-styles.html
=> use typography mixins

d2l-sequence-navigator.html
Doing away with the two step up, link system. Using the sequence-root link as the lesson
=> Stopping the refreshing effect of the navigation menu

components/d2l-module-link.html
bug: empty modules are not displayed because we're counting the number of subentities wrong
=> fix empty module bug

d2l-sequence-navigator.html
We were supporting 3rd and 4th activities, and forgot about the activties with a depth of 2
=> Add d2l-activity-link for activities that have a depth of 2

components/d2l-activity-link.html, components/d2l-inner-module.html, components/d2l-lesson-header.html, components/d2l-outer-module.html, d2l-sequence-navigator.html
hopefully clean up some unused css classes too
=> fix focus effect and rounded corners

components/d2l-inner-module.html, components/d2l-outer-module.html, d2l-sequence-navigator.html, test/d2l-outer-module.html
All of this selectedModule and hasCurrentActivity properties don't seem to have any effect on any behaviour
=> Removing selected module

components/d2l-activity-link.html, components/d2l-inner-module.html, components/d2l-outer-module.html, d2l-sequence-navigator.html, demo/index.html
There are a few issues that will be resolved in January. _Please_ check out the changes and try it out locally as there is a lot going on here. Let me know if you find any issues.
=> Changes for Table of Contents

components/d2l-activity-link.html, components/d2l-lesson-header.html, package-lock.json
=> set the selected background colour of an activity item to the primary

components/d2l-lesson-header.html, package-lock.json
Added default value to fill colour and border stylings to css of the progress bar on Edge, due to a known issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12837456/.
=> Fix progress bar rendering on Edge

demo/index.html, package-lock.json
Added reference of d2l-lesson-header to demo page. Added lesson header to the "Sequence navigator in sidebar" section of demo page.
=> displays lesson header in demo

components/d2l-activity-link.js, components/d2l-lesson-header.js, components/d2l-outer-module.js, components/d2l-sequence-end.js, d2l-sequence-navigator.js, package-lock.json
- Added rounded borders for sidebar
- Made only one edge of the navigator border rounded
- fixed some problems with overlapping borders.
UPDATE:
- Added dynamic sizing of progress bar
=> Border Styling Changes

d2l-sequence-navigator.js, package-lock.json
The extra element we saw was a completion entity that got picked up by the `getSubEntities` function which doesn't have an href.
=> display item list only when href has value

components/d2l-inner-module.js, components/d2l-lesson-header.js, components/d2l-outer-module.js, d2l-sequence-navigator.js, package-lock.json
- Sequence header spans length of sidebar
- Fixed border issues when focusing on a link
- Fixed weird issue on Edge and Firefox ESR where the module-header was not getting scoped properly, so the element would not receive any styles (apparently adding a class fixed this).
=> Fixing sequence header size and other UI bugs

components/d2l-lesson-header.js, demo/index.html, package-lock.json
- Added hover and selected styling to the progress bar, to be consistent with design
- `isLightTheme()` function added to work around issue in Edge with variables in `-ms-fill`
- Added `data-asv-css-vars` attribute to `html` tag in the demo index page (since sequence-viewer page will have this)
=> Added hover and selected styling to progress bar

d2l-sequence-navigator.js, package-lock.json, test/d2l-sequence-navigator.html, test/data/unit3-activity1.json, test/data/unit3-activity2.json, test/data/unit3.json
- Checks the top level of the sequence navigator to filter out unavailable activities (i.e. if the start date is in the future, or if the end date is in the past).
=> Add availability check to nav top level

package-lock.json, package.json
We've release version `1.0.0` of core and I'm trying to switch everything over to it so that BSI can upgrade to it as well. No breaking changes in here.
=> uprading core

d2l-sequence-navigator.js
=> check component properties for passed in css vars first before checking
